### ISSUE TITLE
Integration with last.fm and listenbrainz

### ISSUE THREAD

**Issue by assjdksbak** [MatheusBViana/my-lolla#1]
Hi, i like this project and i think that adding support for last.fm and listenbrainz would be a good addition, since you can also get the artists that you listen to on other platforms like youtube, deezer, etc. 

Thanks :)

**Comment by MatheusBViana** [comment]
Hi! Last.fm already working, I'll see how to include listenbrainz too

**Comment by assjdksbak** [comment]
Thanks! :)
